In [1]:
import yfinance as yf
import numpy as np
import pandas as pd

from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [2]:
hdfc_df= yf.Ticker('HDFCBANK.NS')
#ICICIBANK.NS
#SBIN.NS
#KOTAKBANK.NS
#AXISBANK.NS

In [3]:
hdfc_day= hdfc_df.history(period="max")
hdfc_day_train = hdfc_day['1996-01-01' : '2019-10-31']
hdfc_day_test= hdfc_day['2019-11-01': '2019-12-31']
hdfc_day_train.to_csv("Hdfc.csv")
hdfc_day_test.to_csv("Test.csv")
hdfc_day

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1996-01-01,0.60,0.60,0.58,0.59,350000,0.0,0.0
1996-01-02,0.59,0.60,0.58,0.59,412000,0.0,0.0
1996-01-03,0.59,0.59,0.58,0.59,284000,0.0,0.0
1996-01-04,0.59,0.59,0.58,0.58,282000,0.0,0.0
1996-01-05,0.58,0.59,0.58,0.58,189000,0.0,0.0
...,...,...,...,...,...,...,...
2020-03-04,1178.35,1180.00,1133.10,1148.85,17144435,0.0,0.0
2020-03-05,1153.00,1165.00,1142.75,1151.35,9774854,0.0,0.0
2020-03-06,1125.00,1140.90,1101.00,1134.90,11526783,0.0,0.0
2020-03-09,1110.00,1118.40,1065.00,1107.30,17210295,0.0,0.0
2020-03-11,1105.00,1113.60,1092.00,1107.55,8029081,0.0,0.0

In [4]:
print(hdfc_day_train['Dividends'].value_counts())
print(hdfc_day_train['Stock Splits'].value_counts())

0.00     5861
2.50        2
5.50        2
12.00       1
1.00        1
2.00        1
3.00        1
3.50        1
4.50        1
7.00        1
10.00       1
1.60        1
4.30        1
11.00       1
13.00       1
7.50        1
1.30        1
6.85        1
0.80        1
16.50       1
8.50        1
9.50        1
8.00        1
Name: Dividends, dtype: int64
0.0    5883
2.0       1
5.0       1
Name: Stock Splits, dtype: int64

In [5]:
def ChiSquareTest(data, target):
    result1= list()
    result2= list()
    X= data.drop(target, axis= 1)
    for column in range(X.shape[1]):
        data_crosstab = pd.crosstab(X[X.columns[column]], data[target], margins = False) 
        stat, p, dof, expected = chi2_contingency(data_crosstab)
        
        # interpret test-statistic
        prob = 0.95
        critical = chi2.ppf(prob, dof)
        if not(abs(stat) >= critical):
            result1.append(X.columns[column])
            
        # interpret p-value
        alpha = 1.0 - prob
        if not(p <= alpha):
            result2.append(X.columns[column])
        
    return(result1, result2)

In [6]:
test_statistic_result, p_value_result= ChiSquareTest(hdfc_day_train, 'Close')

In [7]:
print(test_statistic_result)

[]